// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PharmacyManagement.API.Data;

#nullable disable

namespace PharmacyManagement.API.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    partial class PharmacyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.API.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PharmacyManagement.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("integer");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatchNumber = "PCM-2025-001",
                            Category = "Analgesics",
                            CostPrice = 3.20m,
                            CreatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6586),
                            ExpiryDate = new DateTime(2027, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Acetaminophen",
                            IsActive = true,
                            Manufacturer = "PharmaCorp",
                            Name = "Paracetamol 500mg",
                            QuantityInStock = 500,
                            ReorderLevel = 50,
                            UnitPrice = 5.99m,
                            UpdatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6590)
                        },
                        new
                        {
                            Id = 2,
                            BatchNumber = "AMX-2025-042",
                            Category = "Antibiotics",
                            CostPrice = 7.80m,
                            CreatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6609),
                            ExpiryDate = new DateTime(2027, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Amoxicillin",
                            IsActive = true,
                            Manufacturer = "MedLife Labs",
                            Name = "Amoxicillin 250mg",
                            QuantityInStock = 200,
                            ReorderLevel = 30,
                            UnitPrice = 12.50m,
                            UpdatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6609)
                        },
                        new
                        {
                            Id = 3,
                            BatchNumber = "OMP-2025-018",
                            Category = "Gastrointestinal",
                            CostPrice = 4.50m,
                            CreatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6615),
                            ExpiryDate = new DateTime(2027, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Omeprazole",
                            IsActive = true,
                            Manufacturer = "HealthGen",
                            Name = "Omeprazole 20mg",
                            QuantityInStock = 8,
                            ReorderLevel = 25,
                            UnitPrice = 8.75m,
                            UpdatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6615)
                        },
                        new
                        {
                            Id = 4,
                            BatchNumber = "MTF-2025-005",
                            Category = "Antidiabetics",
                            CostPrice = 3.75m,
                            CreatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6618),
                            ExpiryDate = new DateTime(2027, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Metformin HCl",
                            IsActive = true,
                            Manufacturer = "DiaCare Pharma",
                            Name = "Metformin 500mg",
                            QuantityInStock = 350,
                            ReorderLevel = 40,
                            UnitPrice = 6.25m,
                            UpdatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6618)
                        },
                        new
                        {
                            Id = 5,
                            BatchNumber = "ATV-2025-033",
                            Category = "Cardiovascular",
                            CostPrice = 9.20m,
                            CreatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6621),
                            ExpiryDate = new DateTime(2027, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Atorvastatin Calcium",
                            IsActive = true,
                            Manufacturer = "HeartWell Inc",
                            Name = "Atorvastatin 10mg",
                            QuantityInStock = 5,
                            ReorderLevel = 20,
                            UnitPrice = 15.00m,
                            UpdatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6622)
                        },
                        new
                        {
                            Id = 6,
                            BatchNumber = "CTZ-2025-011",
                            Category = "Antihistamines",
                            CostPrice = 2.10m,
                            CreatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6625),
                            ExpiryDate = new DateTime(2028, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Cetirizine HCl",
                            IsActive = true,
                            Manufacturer = "AllerFree Labs",
                            Name = "Cetirizine 10mg",
                            QuantityInStock = 600,
                            ReorderLevel = 60,
                            UnitPrice = 4.50m,
                            UpdatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6625)
                        },
                        new
                        {
                            Id = 7,
                            BatchNumber = "LST-2025-027",
                            Category = "Cardiovascular",
                            CostPrice = 6.50m,
                            CreatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6629),
                            ExpiryDate = new DateTime(2027, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Losartan Potassium",
                            IsActive = true,
                            Manufacturer = "HeartWell Inc",
                            Name = "Losartan 50mg",
                            QuantityInStock = 180,
                            ReorderLevel = 25,
                            UnitPrice = 11.25m,
                            UpdatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6629)
                        },
                        new
                        {
                            Id = 8,
                            BatchNumber = "AZM-2025-009",
                            Category = "Antibiotics",
                            CostPrice = 11.50m,
                            CreatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6633),
                            ExpiryDate = new DateTime(2027, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Azithromycin",
                            IsActive = true,
                            Manufacturer = "MedLife Labs",
                            Name = "Azithromycin 500mg",
                            QuantityInStock = 3,
                            ReorderLevel = 15,
                            UnitPrice = 18.00m,
                            UpdatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6634)
                        },
                        new
                        {
                            Id = 9,
                            BatchNumber = "IBP-2025-015",
                            Category = "Analgesics",
                            CostPrice = 3.00m,
                            CreatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6637),
                            ExpiryDate = new DateTime(2027, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Ibuprofen",
                            IsActive = true,
                            Manufacturer = "PharmaCorp",
                            Name = "Ibuprofen 400mg",
                            QuantityInStock = 450,
                            ReorderLevel = 50,
                            UnitPrice = 6.00m,
                            UpdatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6637)
                        },
                        new
                        {
                            Id = 10,
                            BatchNumber = "VTD-2025-022",
                            Category = "Vitamins",
                            CostPrice = 5.00m,
                            CreatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6690),
                            ExpiryDate = new DateTime(2028, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenericName = "Cholecalciferol",
                            IsActive = true,
                            Manufacturer = "NutriHealth",
                            Name = "Vitamin D3 1000IU",
                            QuantityInStock = 320,
                            ReorderLevel = 35,
                            UnitPrice = 9.99m,
                            UpdatedAt = new DateTime(2026, 4, 14, 6, 48, 0, 835, DateTimeKind.Utc).AddTicks(6690)
                        });
                });

            modelBuilder.Entity("PharmacyManagement.API.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerName = "John Smith",
                            InvoiceNumber = "INV-2026-0001",
                            SaleDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 35.97m,
                            TotalCost = 19.20m
                        },
                        new
                        {
                            Id = 2,
                            CustomerName = "Sarah Johnson",
                            InvoiceNumber = "INV-2026-0002",
                            SaleDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 56.25m,
                            TotalCost = 35.10m
                        },
                        new
                        {
                            Id = 3,
                            CustomerName = "Mike Davis",
                            InvoiceNumber = "INV-2026-0003",
                            SaleDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 27.00m,
                            TotalCost = 13.50m
                        },
                        new
                        {
                            Id = 4,
                            CustomerName = "Emily Clark",
                            InvoiceNumber = "INV-2026-0004",
                            SaleDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 43.74m,
                            TotalCost = 22.50m
                        },
                        new
                        {
                            Id = 5,
                            CustomerName = "David Wilson",
                            InvoiceNumber = "INV-2026-0005",
                            SaleDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 90.00m,
                            TotalCost = 55.20m
                        },
                        new
                        {
                            Id = 6,
                            CustomerName = "Lisa Brown",
                            InvoiceNumber = "INV-2026-0006",
                            SaleDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 18.00m,
                            TotalCost = 9.60m
                        },
                        new
                        {
                            Id = 7,
                            CustomerName = "James Taylor",
                            InvoiceNumber = "INV-2026-0007",
                            SaleDate = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 62.50m,
                            TotalCost = 39.00m
                        });
                });

            modelBuilder.Entity("PharmacyManagement.API.Models.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostPrice = 3.20m,
                            ProductId = 1,
                            Quantity = 6,
                            SaleId = 1,
                            SubTotal = 35.94m,
                            UnitPrice = 5.99m
                        },
                        new
                        {
                            Id = 2,
                            CostPrice = 7.80m,
                            ProductId = 2,
                            Quantity = 3,
                            SaleId = 2,
                            SubTotal = 37.50m,
                            UnitPrice = 12.50m
                        },
                        new
                        {
                            Id = 3,
                            CostPrice = 4.50m,
                            ProductId = 3,
                            Quantity = 2,
                            SaleId = 2,
                            SubTotal = 17.50m,
                            UnitPrice = 8.75m
                        },
                        new
                        {
                            Id = 4,
                            CostPrice = 2.10m,
                            ProductId = 6,
                            Quantity = 6,
                            SaleId = 3,
                            SubTotal = 27.00m,
                            UnitPrice = 4.50m
                        },
                        new
                        {
                            Id = 5,
                            CostPrice = 3.00m,
                            ProductId = 9,
                            Quantity = 5,
                            SaleId = 4,
                            SubTotal = 30.00m,
                            UnitPrice = 6.00m
                        },
                        new
                        {
                            Id = 6,
                            CostPrice = 3.20m,
                            ProductId = 1,
                            Quantity = 2,
                            SaleId = 4,
                            SubTotal = 11.98m,
                            UnitPrice = 5.99m
                        },
                        new
                        {
                            Id = 7,
                            CostPrice = 9.20m,
                            ProductId = 5,
                            Quantity = 4,
                            SaleId = 5,
                            SubTotal = 60.00m,
                            UnitPrice = 15.00m
                        },
                        new
                        {
                            Id = 8,
                            CostPrice = 6.50m,
                            ProductId = 7,
                            Quantity = 2,
                            SaleId = 5,
                            SubTotal = 22.50m,
                            UnitPrice = 11.25m
                        },
                        new
                        {
                            Id = 9,
                            CostPrice = 3.20m,
                            ProductId = 1,
                            Quantity = 3,
                            SaleId = 6,
                            SubTotal = 17.97m,
                            UnitPrice = 5.99m
                        },
                        new
                        {
                            Id = 10,
                            CostPrice = 7.80m,
                            ProductId = 2,
                            Quantity = 5,
                            SaleId = 7,
                            SubTotal = 62.50m,
                            UnitPrice = 12.50m
                        });
                });

            modelBuilder.Entity("PharmacyManagement.API.Models.StockEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("CostPricePerUnit")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("StockEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatchNumber = "PCM-2025-001",
                            CostPricePerUnit = 3.20m,
                            EntryDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(2027, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            ProductId = 1,
                            Quantity = 200,
                            Supplier = "PharmaCorp Direct"
                        },
                        new
                        {
                            Id = 2,
                            BatchNumber = "AMX-2025-042",
                            CostPricePerUnit = 7.80m,
                            EntryDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(2027, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            ProductId = 2,
                            Quantity = 100,
                            Supplier = "MedLife Wholesale"
                        },
                        new
                        {
                            Id = 3,
                            BatchNumber = "OMP-2025-018",
                            CostPricePerUnit = 4.50m,
                            EntryDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(2027, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            ProductId = 3,
                            Quantity = 80,
                            Supplier = "HealthGen Supply"
                        },
                        new
                        {
                            Id = 4,
                            BatchNumber = "MTF-2025-005",
                            CostPricePerUnit = 3.75m,
                            EntryDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(2027, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            ProductId = 4,
                            Quantity = 150,
                            Supplier = "DiaCare Wholesale"
                        },
                        new
                        {
                            Id = 5,
                            BatchNumber = "ATV-2025-033",
                            CostPricePerUnit = 9.20m,
                            EntryDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(2027, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            ProductId = 5,
                            Quantity = 50,
                            Supplier = "HeartWell Direct"
                        },
                        new
                        {
                            Id = 6,
                            BatchNumber = "CTZ-2025-011",
                            CostPricePerUnit = 2.10m,
                            EntryDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(2028, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "",
                            ProductId = 6,
                            Quantity = 300,
                            Supplier = "AllerFree Wholesale"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PharmacyManagement.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PharmacyManagement.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PharmacyManagement.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmacyManagement.API.Models.SaleItem", b =>
                {
                    b.HasOne("PharmacyManagement.API.Models.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyManagement.API.Models.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PharmacyManagement.API.Models.StockEntry", b =>
                {
                    b.HasOne("PharmacyManagement.API.Models.Product", "Product")
                        .WithMany("StockEntries")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PharmacyManagement.API.Models.Product", b =>
                {
                    b.Navigation("SaleItems");

                    b.Navigation("StockEntries");
                });

            modelBuilder.Entity("PharmacyManagement.API.Models.Sale", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
